### ISSUE TITLE
not an issue. just need help

### ISSUE THREAD

**Issue by DaveShotYa** [atsushieno/sf2xrni#7]
I'm not well versed At All when it comes to compiling programs and tools I find on github. This is the 3rd time I've tried tackling putting this together this year and I'm Desperate. I've read the forum post you made on this from over an actual decade ago and it seems that there is supposed to be an exe (sf2xrni.exe) that you run using another tool called "mono" (also don't know what this is). The exe Isn't in the repo anymore and I assume that I'm supposed to make it using the makefile. My problem comes when I try to make it, as the command prompt tells that there's a missing file. No idea what It's looking for or what could be causing it. image attached.
![image](https://github.com/atsushieno/sf2xrni/assets/105587006/6abf4445-6208-4a7d-ac50-afd7b36adf34)

**Comment by atsushieno** [comment]
sf2xrni was a .NET executable which requires .NET runtime (Windows CLR or Mono). This repo never included mono, just like no Java applications contain java.exe. You will have to download either (1) old mono version such as 2.x, and  put `mono` and `mcs` in your PATH, then run `CSC=mcs make`, or (2) .NET Framework 2.x if you could still find it from MS website) for your platform, find `csc.exe` on some path (which used to be placed at `*:\Windows\system32`) then run `make`.

It is an ancient program that you will have to set up such an old environment. Since NRenoiseTools.dll is dead and vanished from the ecosystem, it is not able to simply bring back to life and make sf2xrni build with modern tools anymore.
